### ISSUE TITLE
Rasterize coarse 

### ISSUE THREAD

**Issue by TakWolf** [mooman219/fontdue#32]
SourceHanSansSC-Regular.otf  on logical 24px(Physical 48px)

left is `ab-glyph`, right is `fontdue`
![image](https://user-images.githubusercontent.com/6064962/92215019-c8526600-eec6-11ea-989b-b70faee3763b.png)
 
The smaller the size, the more obvious the effect
on logical 12px(Physical 24px), this is considered the smallest text size.

![image](https://user-images.githubusercontent.com/6064962/92215490-70682f00-eec7-11ea-9e11-efe7549f7b52.png)

**Comment by mooman219** [comment]
![image](https://user-images.githubusercontent.com/865769/92216984-e9c23c00-ee4b-11ea-8752-098d84772b74.png)
I'm not seeing the same coarse edges. This error looks like you're using an incorrect width for your glyphs at some point.

**Comment by TakWolf** [comment]
char 'C' on 24.0px

## ab-glyph:
![image](https://user-images.githubusercontent.com/6064962/92222737-086b1600-eed2-11ea-8e7c-2f479ab8bd05.png)
14 x 19 pixel
``` rust
// with fix the scale error https://github.com/alexheretic/ab-glyph/issues/15
[src/main.rs:28] advance_width = 15.312
[src/main.rs:30] &rect = Rect {
    min: point(1.0, -18.0),
    max: point(15.0, 1.0),
}
// https://github.com/alexheretic/ab-glyph/blob/master/glyph/src/outlined.rs#L163-L173
[src/main.rs:31] rect.width() = 14.0
[src/main.rs:32] rect.height() = 19.0
```

## fontdue:
![image](https://user-images.githubusercontent.com/6064962/92222754-0f922400-eed2-11ea-94cf-f48333e72ff3.png)
14 x 20 pixel
``` rust
[src/main.rs:49] metrics = Metrics {
    width: 14,
    height: 20,
    advance_width: 15.312,
    advance_height: 24.0,
    bounds: AABB {
        xmin: 1.392,
        xmax: 14.448,
        ymin: -0.312,
        ymax: 17.928,
    },
}
[src/main.rs:50] metrics.bounds.xmax - metrics.bounds.xmin = 13.056 // != 14.0
[src/main.rs:51] metrics.bounds.ymax - metrics.bounds.ymin = 18.24 // != 20.0
```

----------------------
The results of rasterization are almost the same.(fontdue with a 1px top blank, but this is unimportance)
But fontdue's bounds is not correct(UV mapping not fix pixel size, smaller than the real size), so the rendering looks incomplete.

**Comment by TakWolf** [comment]
This is what I fix bounds:

``` rust
        let xmax = metrics.width as f32 + metrics.bounds.xmin;
        let ymax = metrics.height as f32 + metrics.bounds.ymin;
```

![image](https://user-images.githubusercontent.com/6064962/92224668-b4adfc00-eed4-11ea-80d2-7b850f6d560c.png)

The size rendering looks correct.But position still has problems.(minxy not fix)

![image](https://user-images.githubusercontent.com/6064962/92225194-7533df80-eed5-11ea-9b46-1fa034a073ec.png)
![image](https://user-images.githubusercontent.com/6064962/92225281-91d01780-eed5-11ea-8513-fb97406033a8.png)

**Comment by mooman219** [comment]
I pushed a fix for the padding issue.

**Comment by TakWolf** [comment]
> Width and height are always usize and will always contain the glyph. Bounds is f32 because it represents the true bounding > box around the glyph, and can be fractional. This fractional component is required for subpixel layout.

I still can’t calculate the UV coordinates accurately. For example:

```rust
[src/main.rs:51] metrics = Metrics {
    width: 14,
    height: 19,
    advance_width: 15.312,
    advance_height: 24.0,
    bounds: AABB {
        xmin: 1.392,
        xmax: 14.448,
        ymin: -0.312,
        ymax: 17.928,
    },
}
[src/main.rs:52] metrics.bounds.xmax - metrics.bounds.xmin = 13.056
[src/main.rs:53] metrics.bounds.ymax - metrics.bounds.ymin = 18.24
```

The bitmap is 14 * 19, if using pixel uv mapping, it is (0.0, 0.0) (1.0, 1.0)
But if as bounds uv mapping, it is:
uvx0 = 0; // maybe not 0, because rasterization may not start from zero, this is why cause the position error.
uvy0 = 0;
uvy1 = (metrics.bounds.xmax - metrics.bounds.xmin) / metrics.width;
uvy2 = (metrics.bounds.ymax - metrics.bounds.ymin) / metrics.height;
So: (uvx0, uvy0) (uvx1, uvy1) =>  (0.0, 0.0) -> (0.93257143, 0.96)

This increases the difficulty of drawing.We can use bounds for the real coordinate, but can not use real uv from the bitmap.

**Comment by TakWolf** [comment]
I think there are two options:
1. like ab-glyph always based on pixels, although the bounds is not the real value, but offset by rasterization, the screen result is correct.
2.There is another params in Metrics like `uv_ bounds` to describe what the bounds mapping with bitmap.

**Comment by mooman219** [comment]
I'm confused on what you mean UV being hard to calculate, the width and height are correct, and you should use the whole bitmap and not take a subset of it. You do not want to take anything smaller than the width and height as they're the smallest unit the glyph can be represented correctly. The extra fraction of a pixel empty space around the glyph is required because the font specifics it to be there. In terms of correctness: ab_glyph is giving you incorrect results based on what the font specifies, unless I'm misunderstanding your pipeline.

**Comment by TakWolf** [comment]
Width and height are always usize and will always contain the glyph.Bounds is f32 because it represents the true bounding box around the glyph, so they are not match, there is always a one pixel offset.
If we use bitmap, we must know what the rounding bounds.Or we use bounds, and must know what the precise region in bitmap.

**Comment by mrDIMAS** [comment]
I have had somewhat same issues with positioning of glyphs. At first I used bounding box (metrics.xmin, metrics.xmax, metrics.ymin, metrics.ymax) values to calculate width (xmax - xmin) and height (ymax - ymin) of a glyph, and on layout stage (I use my own layout, not the crate's one) those values resulted in "jumping" glyphs, offset was small - something about 1px. I fixed this by switching to metrics.width and metrics.height. So real metrics of glyph are: 

```
let left = metrics.xmin;
let top = metrics.ymin;
let width = metrics.width as f32;
let height = metrics.height as f32;
```

This was a bit confising and I spent about 2 hours trying to understand why layout is so weird.

**Comment by mooman219** [comment]
This is a readability issue with the docs, not a technical issue. I would like to explore ways of making the right solution more obvious in the documentation/structures.

The aabb bounds of a glyph will not match with the width/height dimensions of the glyph. The bounds define the inner bounding box that the font specifies. This is the smallest box that encapsulates the glyph, and is defined in fractional units. It is defined in fractional units because the outline for the glyph does not align to the pixel grid, and is important to fractional positioning if the layout tool is aware. Take this example of:

![image](https://user-images.githubusercontent.com/865769/92333817-4afd3180-f03d-11ea-952f-989a9e49fa51.png)

```
Key:
Grid: Grey
Baseline: Black
Glyph: Blue
Glyph bounds: Purple
Glyph pixel bounds: Orange
```

Because the aabb bounds (purple) do not align with the pixel grid (grey), the bitmap fontdue produces is the smallest bounding box that encapsulates the full aabb (orange) rasterized. The width and height fields represent the orange box's dimensions. 

---

One solution I can see is replacing width/height/bounds with inner_ bounds (fractional, not grid aligned, the purple box), and outer_bounds (grid aligned, matches bitmap, the orange box), and documenting them as such. This would be a breaking change downstream but we're experimental and this is an issue.

Would that make it more clear if you were seeing the API for the first time?

**Comment by mrDIMAS** [comment]
I think it would be good to do the same as [FreeType does](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_glyphslotrec) - it has `bitmap_left` and `bitmap_top` fields at glyph description, and separate field `bitmap` which has its own fields `width`, `rows` (height). This in my opinion is less confusing because in most cases you need to know how to offset rasterized glyph in pixels, so there will be no problems with rounding and such stuff.

**Comment by TakWolf** [comment]
(v0.3.0) Some glyph rasterize incorrect when `settings.enable_offset_bounding_box = true`(default is true)

-----------------------------------------
Zpix-beta-v3.0.2-beta.0.ttf
char = 't'
px = '12.0' 

settings.enable_offset_bounding_box = true

![image](https://user-images.githubusercontent.com/6064962/93432517-3d2a9480-f8f8-11ea-860e-50dbc7527bdb.png)

settings.enable_offset_bounding_box = false
 
![image](https://user-images.githubusercontent.com/6064962/93432621-621f0780-f8f8-11ea-8ded-a1d0b965e283.png)

-----------------------------------------
SourceHanSansSC-Regular.otf
char = 'd'
px = '24.0' 

settings.enable_offset_bounding_box = true

![image](https://user-images.githubusercontent.com/6064962/93433564-87604580-f8f9-11ea-8a71-5ec345ef6366.png)

settings.enable_offset_bounding_box = false

![image](https://user-images.githubusercontent.com/6064962/93433630-9f37c980-f8f9-11ea-99fb-e2850bf5b851.png)

======================================

If use `settings.enable_offset_bounding_box = false`, rasterize position will incorrect(usually 1 pixel up offset)

-------------------------------------------------
SourceHanSansSC-Regular.otf
px = 12.0

settings.enable_offset_bounding_box = true

![image](https://user-images.githubusercontent.com/6064962/93435050-757fa200-f8fb-11ea-8e23-38e867d023c0.png)

settings.enable_offset_bounding_box = false

![image](https://user-images.githubusercontent.com/6064962/93435080-803a3700-f8fb-11ea-8bea-2ec657462564.png)

-------------------------------------------------
SourceHanSansSC-Regular.otf
px = 24.0

settings.enable_offset_bounding_box = true

![image](https://user-images.githubusercontent.com/6064962/93433796-df974780-f8f9-11ea-9a03-6198ec0fcf07.png)
![image](https://user-images.githubusercontent.com/6064962/93434417-b6c38200-f8fa-11ea-9a16-5c27927ded1f.png)

settings.enable_offset_bounding_box = false

![image](https://user-images.githubusercontent.com/6064962/93433941-11101300-f8fa-11ea-87a8-d0df8178674c.png)
![image](https://user-images.githubusercontent.com/6064962/93434195-66e4bb00-f8fa-11ea-947d-0c22c78957af.png)

----------------------------------------------------
SourceHanSansSC-Regular.otf
char = 'n'
px = 24.0

settings.enable_offset_bounding_box = true
![image](https://user-images.githubusercontent.com/6064962/93435479-1a9a7a80-f8fc-11ea-8688-e67cc2abb459.png)

settings.enable_offset_bounding_box = false
![image](https://user-images.githubusercontent.com/6064962/93435608-4158b100-f8fc-11ea-8982-3492b4be6991.png)

----------------------------------------------------
SourceHanSansSC-Regular.otf
char = 'h'
px = 24.0

settings.enable_offset_bounding_box = true
![image](https://user-images.githubusercontent.com/6064962/93436423-5da91d80-f8fd-11ea-9210-a5caabaac302.png)

settings.enable_offset_bounding_box = false
![image](https://user-images.githubusercontent.com/6064962/93436648-a6f96d00-f8fd-11ea-8b6c-76a4df938703.png)

 ====================================

What the problem does `enable_offset_bounding_box` to fix.
If means enable_offset_bounding_box=false, rasterize will always start with position(0.0, 0.0) in bitmap?
In this case ,should fix metrics.xmin and metrics.ymin with offset?

**Comment by mooman219** [comment]
I made a typo in the change, I'll fix and push it in like 8 hours. I wrote `(offset_y, offset_y)` instead of `(offset_x, offset_y)`

**Comment by mooman219** [comment]
https://github.com/mooman219/fontdue/commit/04447015f81522f5f168b61f9aa76d6428afe3fb Fixed

**Comment by mooman219** [comment]
Metrics should be fixed as well. Does 0.3.2 work for you two? @mrDIMAS, @TakWolf

**Comment by TakWolf** [comment]
So far, everything is working well for me. v0.3.2

From top to bottom are  `SourceHanSansSC-Regular.otf` as 24px in chrome, fontdue and ab-glyph:
![image](https://user-images.githubusercontent.com/6064962/93565724-6877b700-f9be-11ea-9429-5ff1aba73dd0.png)

**Comment by mooman219** [comment]
Looks good. Does the new metrics API that's in 0.3.2 (below) clear up the confusion as well?
```rust
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Metrics {
    /// Whole pixel offset of the left-most edge of the bitmap. This may be negative to reflect the
    /// glyph is positioned to the left of the origin.
    pub xmin: i32,
    /// Whole pixel offset of the bottom-most edge of the bitmap. This may be negative to refelct
    /// the glyph is positioned below the baseline.
    pub ymin: i32,
    /// The width of the bitmap in whole pixels.
    pub width: usize,
    /// The height of the bitmap in whole pixels.
    pub height: usize,
    /// Advance width of the glyph in subpixels. Used in horizontal fonts.
    pub advance_width: f32,
    /// Advance height of the glyph in subpixels. Used in vertical fonts.
    pub advance_height: f32,
    /// The bounding box that contains the glyph's outline at the offsets specified by the font.
    /// This is always a smaller box than the bitmap bounds.
    pub bounds: OutlineBounds,
}
```

**Comment by mrDIMAS** [comment]
Perfect! This API is much more clear and rendered text looks nice.
